sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '4'
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
